services:
  localdb:
    container_name: hana7db
    image: mysql:8.0
    ports:
      - 3309:3306
      #맥에서는 3309 도커에서는 3306
    environment:
      MYSQL_ROOT_PASSWORD: TestdbRoot
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log_bin_trust_function_creators=1
      - --innodb_ft_min_token_size=2
      - --innodb_ft_server_stopword_table=schooldb/StopWord #testdb 따로 안만듷고 schooldb에서 했기때문에 걍 여기서도

    volumes:
      - ./mysql:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf #가상의 cnf 추가?? 밖으로 빼낸 이유는 git에 올리려고
